### ISSUE TITLE
Toggle InfluxDB Health Check

### ISSUE THREAD

**Issue by iwvelando** [cdzombak/ecobee_influx_connector#10]
Hi there,

I just started trying out your tool and so far so good. The only issue is in my case I had to disable the InfluxDB health check. In my setup I've migrated to InfluxDB 2 but still use Kapacitor for various automations. As a result I use a telegraf instance as a router where it receives all data points and then tees them off to both InfluxDB 2 and to Kapacitor. This telegraf router doesn't support the health check API so this utility fails immediately.

I'm going to try this out for a little while and hopefully this weekend if nobody beats me to it I'll be able to find some time to contribute a patch to allow this.

**Comment by cdzombak** [comment]
I see. I'd accept such a patch, provided the health check is still on by default.

**Comment by iwvelando** [comment]
Please see https://github.com/cdzombak/ecobee_influx_connector/pull/11

**Comment by cdzombak** [comment]
Closed by ea1c5486663d843c479cb172180d796c928cac2e
