### ISSUE TITLE
Add weather symbol and sky to InfluxDB

### ISSUE THREAD

**Issue by iwvelando** [cdzombak/ecobee_influx_connector#12]
I have an automation I'd like to perform where I alter the ecobee comfort setting based on some weather conditions. As far as I can tell this data is not currently collected from this software in the ecobee_weather measurement, but it is available in the WeatherForecast struct. Based on https://www.ecobee.com/home/developer/api/documentation/v1/objects/WeatherForecast.shtml I think that the WeatherSymbol field is the most suitable, but Sky would be useful for correlation (for example: WeatherSymbol may indicate windy but Sky could clarify if it's clear or not regardless).

I will be adding this in a local build to complete my project. Would you be interested in a patch that adds this to fields like `weather_symbol` for WeatherSymbol and `sky` for Sky? 

Edit: I've added this in my fork, happy to PR it back to here if you're interested though https://github.com/iwvelando/ecobee_influx_connector/commit/2218356c1f79baf2c37f100f70f40bce0d312276

**Comment by cdzombak** [comment]
That looks good. If you send a PR I'll accept it. Thanks!
