### ISSUE TITLE
Influx buckets

### ISSUE THREAD

**Issue by mindedc** [cdzombak/ecobee_influx_connector#18]
Apparently this refers to "buckets" in influx but I don't seem to have "buckets". I do however have "databases" but I don't see where to specify which database to write to. Is there some kind of undocumented parameter for the database? I've looked through the source but don't see anything.

**Comment by cdzombak** [comment]
I assume you're running InfluxDB 1.x. "Buckets" are new in InfluxDB 2; they identify "a named location where time series data is stored" ([reference](https://docs.influxdata.com/influxdb/v1.8/concepts/glossary/#bucket)).

For Influx 1.x, use `database_name/retention_policy` as your bucket name, or just the database name to use the default retention policy. I'm still running Influx 1.x at home. In my config, I have `"influx_bucket": "dzhome"` which writes to the `dzhome` database under the default retention policy.

The Influx documentation is not clear about this change, unfortunately.
