### ISSUE TITLE
Sensor data not captured

### ISSUE THREAD

**Issue by shortyjacobs** [cdzombak/ecobee_influx_connector#20]
Running the find-thermostats returns only one ID, the main ecobee unit.  I have 4 remote sensors as well connected to that main unit: is there a way to pull the temperature/humidity data from those as well?

**Comment by cdzombak** [comment]
The application does this already, in the `for` loop starting here: https://github.com/cdzombak/ecobee_influx_connector/blob/main/main.go#L276

Each sensor is not an independent thermostat, so it's not reported as such; they are each written as an `ecobee_sensor` data point.

**Comment by cdzombak** [comment]
My setup to graph this in Grafana looks like this:
<img width="549" alt="Screen Shot 2022-07-05 at 11 23 35" src="https://user-images.githubusercontent.com/102904/177362703-4f8863c8-8a4d-4a5d-ace3-4ead0d6c34d7.png">
