### ISSUE TITLE
InfluxDB 2 Auth Error

### ISSUE THREAD

**Issue by besselfunct** [cdzombak/ecobee_influx_connector#21]
System = Raspberry Pi B3+
OS = Raspbian Lite
InfluxDB = v2.3
Using Docker

Hi,
I've gotten pretty far with this on my own, but I've hit a wall and I'm not exactly sure what's going wrong on my end.

When I run `docker start -i ecobee` I get the following output:
```
2022/08/11 13:11:48 latest runtime interval available is 154
Thermostat conditions at 2022-08-11 12:45:00 +0000 UTC:
	current temperature: 74.4 degF
	heat set point: 68.0 degF
	cool set point: 74.0 degF
	demand management offset: -0.2
	current humidity: 65%
	humidity set point: 0
	HVAC mode: heatOff
	fan runtime: 0 seconds
	humidifier runtime: 0 seconds
	heat pump 1 runtime: 0 seconds
	heat pump 2 runtime: 0 seconds
	heat 1 runtime: 0 seconds
	heat 2 runtime: 0 seconds
	cool 1 runtime: 0 seconds
	cool 2 runtime: 0 seconds
2022/08/11 13:11:48 influxdb2client E! Write error: unauthorized: unauthorized access
2022/08/11 13:11:48 influxdb2client E! Write error: unauthorized: unauthorized access
```
I've tried many variations on the JSON file to try to get things working.
I've verified that the API token is correct, and I've tried changing the bucket from the pretty name to the Bucket ID listed in the dashboard.
I've also tried creating a v1 Auth Token with credentials, as I wasn't certain if this script was compatible with InfluxDB 2.x, but I haven't managed to get past this `unauthorized access` error.

Any thoughts as to what might be causing this?

**Comment by Age83212** [comment]
I am having this exact issue as well. Any chance this can be addressed?

**Comment by badincite** [comment]
> I am having this exact issue as well. Any chance this can be addressed?

How did you even get past the spammed pin code? I couldn't get it entered fast enough.

**Comment by theonlytruebigmac** [comment]
This is just a product of poor documentation. I reviewed the code and found that the InfluxUser and InfluxPass need to be null and just token and bucket need their values. This seems to fix the auth error. Make sure your token has access to the bucket.

`const influxTimeout = 3 * time.Second
	authString := ""
	if config.InfluxUser != "" || config.InfluxPass != "" {
		authString = fmt.Sprintf("%s:%s", config.InfluxUser, config.InfluxPass)
	} else if config.InfluxToken != "" {
		authString = fmt.Sprintf("%s", config.InfluxToken)
	}`

**Comment by theonlytruebigmac** [comment]
> > I am having this exact issue as well. Any chance this can be addressed?
> 
> How did you even get past the spammed pin code? I couldn't get it entered fast enough.

I had success running this directly from my docker server:
`sudo docker run --rm -it -v ~/.appdata/ecobee_influx_connector/:/config cdzombak/ecobee_influx_connector /go/src/app/ecobee_influx_connector -config "/config/config.json" -list-thermostats`

Make sure that your 'work_dir' is /config so that the cache is loaded.

**Comment by Age83212** [comment]
Thanks @theonlytruebigmac 

I updated my config file to set the UN and PW to null as follows:
"influx_user": "",
 "influx_password": "",

Thanks for your help.

Any chance you can figure out how to modify the application to allow for the option to report in Deg C for us metric folks?

**Comment by theonlytruebigmac** [comment]
@Age83212 I don't see why I couldn't try, it does look like incorporating it might time some time but I'll give it a shot. If your final destination is Grafana like me, you could do the conversion at the graphing destination. 

Here is an example of an ESP32 project I'm working on. I just use map to convert the existing values to F when they come in C.

`from(bucket: "ESPHome")
  |> range(start: 0, stop: now())
  |> filter(fn: (r) => r.device == "AlphaTest-Office")
  |> filter(fn: (r) => r._field == "Temperature")
  |> map(fn: (r) => ({r with _value: r._value * 1.8 + 32.0}))`

**Comment by Age83212** [comment]
@theonlytruebigmac Grafana is my final destination and I have set it up today with a map function. Either I'll keep it this way or maybe even setup the query as a task to "down sample" to Celsius. I wouldn't spend your time trying to modify on account of my request.

Thanks for the query example as well.

Cheers

**Comment by theonlytruebigmac** [comment]
@Age83212 well my curiosity (and adhd) has bested me. I'm really interested in trying to use an ESP32 as an ecobee temp sensor so I can get out of paying 80usd for two. I'mma dig into the API and will most likely already use some of this go to do so. Def not high on the list right now but if I do get it working youll be the first to know! cheers!

**Comment by cdzombak** [comment]
@theonlytruebigmac @Age83212 I do not currently have an Ecobee or an InfluxDB 2 instance set up to experiment with.

If you could please send a pull request for [the README](https://github.com/cdzombak/ecobee_influx_connector#faq), adding an FAQ about how to set configure the connector with InfluxDB 2, I would really appreciate it!

**Comment by cdzombak** [comment]
@Age83212 I added notes in #7 about what it would take to support Celsius.

Please see my comment in https://github.com/cdzombak/ecobee_influx_connector/issues/7#issuecomment-991209993 for a suggested workaround: you could just let the connector write Fahrenheit to your InfluxDB and set up an InfluxDB Task to create new data points with temperatures converted to Celsius. That would avoid having to modify this program at all, and that might be an easier way to do this.

Handling this in Grafana as suggested in https://github.com/cdzombak/ecobee_influx_connector/issues/21#issuecomment-1407834893 might be even easier.

**Comment by theonlytruebigmac** [comment]
Been a while but finally had time to sit down and work out the F to C. I submitted a PR, I may still need to double check the humdity/dewpoint values as I'm not sure if those will need adjusting or not.
