### ISSUE TITLE
Better handle Ecobee API outages

### ISSUE THREAD

**Issue by Cuzzo01** [cdzombak/ecobee_influx_connector#32]
I've had a number of instances where the script has crashed due to receiving non-200 status codes from Ecobee. My assumption is they've had outages (instead of the script having issues) since I've seen 403s and 500s. 

Either way, the script doesn't seem to handle these outages very gracefully. Looks to me like it does instant retries 10 times before exiting. Seems like it would be preferable to do exponential [back offs](https://en.wikipedia.org/wiki/Exponential_backoff) for the retries, possibly with a config variable for how many reties to do before exiting.

Here are the logs showing the instant reties. I've configured the container to automatically restart on exit, which is why you can see multiple sets of reties.
![Screenshot 2023-04-14 094452](https://user-images.githubusercontent.com/2738751/232077019-d165c2d2-c414-4922-83db-f06fa8cbd223.png)

**Comment by cdzombak** [comment]
I've pushed a tweak for retry behavior in https://github.com/cdzombak/ecobee_influx_connector/commit/60aa72e3b632b50015ac83b575036b99d2e38905 . This commit:

- Limits all Ecobee & InfluxDB operations to 3 retries
- Sets the initial retry delay to 5s for the main update function (which calls the Ecobee API)
- Sets the initial retry delay to 1s for InfluxDB writes

Please note that even prior to this commit, in the screenshot you've posted, retries *are* using exponential backoff. The code uses the[ avast/retry-go](https://github.com/avast/retry-go) library, and its default behavior is to allow 10 retries, with an initial delay of 100ms, and a backoff + random delay strategy: https://github.com/avast/retry-go/blob/ce731f6114d3f1b81d16110b9f7d6a8637b1339b/retry.go#L83-L92

**Comment by cdzombak** [comment]
Finally, I don't currently have an Ecobee thermostat, so please report back if this change isn't working well for you.
