### ISSUE TITLE
Libwx Humidity format change

### ISSUE THREAD

**Issue by kb1ibt** [cdzombak/ecobee_influx_connector#38]
I upgraded my docker image to the new one using the updated libwx code and it started throwing errors about the format of the recommended max humidity now being a string instead of an integer.
`unprocessable entity: failure writing points to database: partial write: field type conflict: input field "recommended_max_indoor_humidity" on measurement "ecobee_weather" is type string, already exists as type integer dropped=1 `

**Comment by cdzombak** [comment]
That's really odd, since the change was basically moving existing code around the the relative humidity measurement is still an int. Could you please try with the latest `main` - commit c182bb86af642be943e65a90367af64d2f3a8b1c - and let me know if that fixes this?

**Comment by ablyler** [comment]
That is odd; I cannot reproduce this issue with the latest version.
