### ISSUE TITLE
Initial setup fails

### ISSUE THREAD

**Issue by canerdianeh** [cdzombak/ecobee_influx_connector#57]
Per the documentation (such as it is), the initial setup to generate the application connection PIN throws the following error. I don't know if this is due to a change in the API on Ecobee's end, a server outage on Ecobee's end, or a bug in the code. 

**ecobee_influx_connector -list-thermostats -config ~/.ecobee_influx_connector/config.json**
2024/01/17 15:29:22 error fetching thermostats: error on get request: Get "https://api.ecobee.com/1/thermostat?json=%7B%22selection%22%3A%7B%22selectionType%22%3A%22registered%22%2C%22selectionMatch%22%3A%22%22%2C%22includeRuntime%22%3Afalse%2C%22includeExtendedRuntime%22%3Afalse%2C%22includeElectricity%22%3Afalse%2C%22includeSettings%22%3Afalse%2C%22includeLocation%22%3Afalse%2C%22includeProgram%22%3Afalse%2C%22includeEvents%22%3Afalse%2C%22includeDevice%22%3Afalse%2C%22includeTechnician%22%3Afalse%2C%22includeUtility%22%3Afalse%2C%22includeManagement%22%3Afalse%2C%22includeAlerts%22%3Afalse%2C%22includeWeather%22%3Afalse%2C%22includeHouseDetails%22%3Afalse%2C%22includeOemCfg%22%3Afalse%2C%22includeEquipmentStatus%22%3Afalse%2C%22includeNotificationSettings%22%3Afalse%2C%22includePrivacy%22%3Afalse%2C%22includeVersion%22%3Afalse%2C%22includeSecuritySettings%22%3Afalse%2C%22includeSensors%22%3Afalse%2C%22includeAudio%22%3Afalse%7D%2C%22page%22%3A%7B%22totalPages%22%3A0%2C%22pageSize%22%3A0%2C%22total%22%3A0%7D%7D": error on initial authentication: invalid server response: 400 Bad Request

**Comment by cdzombak** [comment]
Hm, thanks for the report. Unfortunately I do not currently have an Ecobee setup, which limits the troubleshooting I can do.

Can you please share (with redaction of sensitive information) the contents of `~/.ecobee_influx_connector/config.json`?
