### ISSUE TITLE
docker setup flow is rough

### ISSUE THREAD

**Issue by wez** [cdzombak/ecobee_influx_connector#9]
The initial setup for docker isn't especially nice, because it's not possible to perform the interactive pin/authorization flow until the full config file is setup and the service is up and running: there's a chicken and egg issue with knowing the thermostat_id and then the docker logs are spammed with multiple pin association attempts

**Comment by cdzombak** [comment]
Documentation around initial setup is rough, especially for Docker.

I am able to perform the initial auth flow using the Docker image, with the following command:

```
docker run --rm -it -v /Users/cdzombak/tmp/ecobee:/config cdzombak/ecobee_influx_connector /go/src/app/ecobee_influx_connector -config "/config/config.json" -list-thermostats
```

My `/Users/cdzombak/tmp/ecobee` directory contains one file, `config.json`:

```
{
  "api_key": "xxx",
  "work_dir": "/config"
}
```

**Comment by besselfunct** [comment]
It's worth noting that in this instance, the `thermostat_id` parameter was the same as the serial number on my unit. I'm not sure if that's always the case, but it can be obtained from the online dashboard.

**Comment by Codesmith512** [comment]
I'm gonna try to set this up myself over the next few days/weeks using docker, and I don't mind writing and committing some code -- what's the best way to solve this for future users? The couple ideas I've got are

1. Just add a blurb to the readme and call it good enough
2. Upload a `docker-compose.yml` that has a profile for setup and a profile for running
3. Walk the user through setup -- if a config file isn't present, tell them to make one, and exit. From there, an interactive terminal could provide directions for setup; If an API key is missing, give them directions and a URL to get one, and write it to the config. Walk them through the pin. Maybe a questionnaire about the specific features they want. Once setup, it just runs non-interactive.

Obviously 3. is the most work, but if that sounds good to the maintainers, I've been looking for an excuse to do some go coding lol.

**Comment by cdzombak** [comment]
Noting that #37 includes some documentation improvements around this.
